#!/bin/sh
set -e

CONFIG_FILE="/data/config.yaml"

# ---------------------------------------------------------------------------
# Helper: generate a random local API key (ccgw-<48 hex chars>)
# ---------------------------------------------------------------------------
gen_api_key() {
  hex=$(dd if=/dev/urandom bs=24 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n')
  echo "ccgw-${hex}"
}

# ---------------------------------------------------------------------------
# Helper: generate config.yaml from environment variables
# ---------------------------------------------------------------------------
generate_config() {
  local api_key="${API_KEY:-$(gen_api_key)}"
  local cc_api_key="${CC_API_KEY:-}"
  local cc_base_url="${CC_BASE_URL:-https://api.commandcode.ai}"
  local host="${HOST:-0.0.0.0}"
  local port="${PORT:-11434}"
  local exclude_models="${EXCLUDE_MODELS:-gpt-,claude-,gemini-}"

  # Build YAML exclude_models list
  if [ -z "$exclude_models" ]; then
    yaml_exclude="[]"
  else
    yaml_exclude="[$(echo "$exclude_models" | sed 's/, */, /g')]"
  fi

  cat > "$CONFIG_FILE" << EOF
# cmdcode2api configuration — generated by entrypoint.sh
api_key: "${api_key}"
commandcode:
  api_key: "${cc_api_key}"
  base_url: "${cc_base_url}"
host: "${host}"
port: ${port}
exclude_models: ${yaml_exclude}
EOF

  # Print the generated local key when it was auto-generated
  if [ -z "${API_KEY:-}" ]; then
    echo ""
    echo "  ╔══════════════════════════════════════════════════╗"
    echo "  ║  Local API key: ${api_key}  ║"
    echo "  ║                                                  ║"
    echo "  ║  Use this as the Bearer token in your clients.   ║"
    echo "  ║  Set API_KEY env var for a fixed key on restarts.║"
    echo "  ╚══════════════════════════════════════════════════╝"
    echo ""
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
case "${1:-server}" in
  server)
    # Create config from env vars if it doesn't exist yet
    if [ ! -f "$CONFIG_FILE" ]; then
      echo "[entrypoint] Creating config.yaml from environment variables..."
      generate_config
    fi

    # Apply environment variable overrides (always)
    [ -n "${CC_API_KEY:-}" ] && sed -i "s|^  api_key:.*|  api_key: ${CC_API_KEY}|" "$CONFIG_FILE"
    [ -n "${API_KEY:-}" ]     && sed -i "s|^api_key: .*|api_key: \"${API_KEY}\"|" "$CONFIG_FILE"
    [ -n "${HOST:-}" ]        && sed -i "s|^host:.*|host: \"${HOST}\"|" "$CONFIG_FILE"
    [ -n "${PORT:-}" ]        && sed -i "s|^port:.*|port: ${PORT}|" "$CONFIG_FILE"

    echo "[entrypoint] Starting cmdcode2api..."
    exec /cmdcode2api
    ;;

  oauth)
    cat >&2 <<'EOF'
Error: OAuth flow is not available in Docker.

Get your Command Code API key from the web dashboard instead:

  1. Go to https://commandcode.ai/studio/
  2. Navigate to API Keys
  3. Click "Generate API Key"

Then run the container with:

  docker run ... -e CC_API_KEY="sk-..." ...
EOF
    exit 1
    ;;

  sh|bash)
    exec /bin/sh
    ;;

  *)
    exec "$@"
    ;;
esac
